In [1]:
import pandas as pd
import matplotlib.pyplot as plt

import os
import glob
import tqdm

import numpy as np
import nibabel as nib
import SimpleITK as sitk
from PIL import Image
from scipy.ndimage import zoom
import shutil

In [2]:
meta=pd.read_csv("/mnt/ai_neuro/august_kun/miccai/ContourDiff/data/domain_2/meta")
meta=meta.sort_values("image_name")
meta=meta.reset_index()
meta

index  Unnamed: 0                         image_name  \
0      22658       22658       Case_00001_0000_slice000.png   
1      13407       13407       Case_00001_0000_slice001.png   
2        788         788       Case_00001_0000_slice002.png   
3       3926        3926       Case_00001_0000_slice003.png   
4      20007       20007       Case_00001_0000_slice004.png   
...      ...         ...                                ...   
29511  11504       11504  FLARE22_Tr_0050_0000_slice090.png   
29512  20479       20479  FLARE22_Tr_0050_0000_slice091.png   
29513   3821        3821  FLARE22_Tr_0050_0000_slice092.png   
29514  17288       17288  FLARE22_Tr_0050_0000_slice093.png   
29515  25402       25402  FLARE22_Tr_0050_0000_slice094.png   

                            contour_name  
0           Case_00001_0000_slice000.png  
1           Case_00001_0000_slice001.png  
2           Case_00001_0000_slice002.png  
3           Case_00001_0000_slice003.png  
4           Case_00001_0000_slice004.png  
...                                  ...  
29511  FLARE22_Tr_0050_0000_slice090.png  
29512  FLARE22_Tr_0050_0000_slice091.png  
29513  FLARE22_Tr_0050_0000_slice092.png  
29514  FLARE22_Tr_0050_0000_slice093.png  
29515  FLARE22_Tr_0050_0000_slice094.png  

[29516 rows x 4 columns]

In [3]:
paths=sorted(glob.glob("/mnt/ai_neuro/august_kun/miccai/ContourDiff/data/ct_2_mr/*.png"))
len(paths)

29516

In [19]:
# img=glob.glob("/mnt/ai_neuro/august_kun/miccai/ContourDiff/data/domain_3/contours/*.png")
# for i in img:
#     n_=os.path.basename(i)
#     if n_.split("_")[0]=="FLARE22":
#         if len(n_.split("_"))<5:
#             os.remove(i)
#     else:
#         if len(n_.split("_"))<4:
#             os.remove(i)

In [ ]:
# os.remove("/mnt/ai_neuro/august_kun/miccai/ContourDiff/data/domain_2/contours/Case_00003_slice000.png")

In [5]:
new_imge=[]
new_contour=[]
cases=[]

for i,rows in meta.iterrows():
    name=rows["image_name"]
    name_=os.path.basename(name)
    for j in paths:
        have_=os.path.basename(j)
        if name_==have_:
            new_imge.append(name)
            new_contour.append(rows["contour_name"])


In [6]:
df=pd.DataFrame({"image_name":new_imge,"contour_name":new_contour})
df

image_name                       contour_name
0           Case_00001_0000_slice000.png       Case_00001_0000_slice000.png
1           Case_00001_0000_slice001.png       Case_00001_0000_slice001.png
2           Case_00001_0000_slice002.png       Case_00001_0000_slice002.png
3           Case_00001_0000_slice003.png       Case_00001_0000_slice003.png
4           Case_00001_0000_slice004.png       Case_00001_0000_slice004.png
...                                  ...                                ...
26594  FLARE22_Tr_0050_0000_slice090.png  FLARE22_Tr_0050_0000_slice090.png
26595  FLARE22_Tr_0050_0000_slice091.png  FLARE22_Tr_0050_0000_slice091.png
26596  FLARE22_Tr_0050_0000_slice092.png  FLARE22_Tr_0050_0000_slice092.png
26597  FLARE22_Tr_0050_0000_slice093.png  FLARE22_Tr_0050_0000_slice093.png
26598  FLARE22_Tr_0050_0000_slice094.png  FLARE22_Tr_0050_0000_slice094.png

[26599 rows x 2 columns]

In [7]:
cases=[]
for i in df["image_name"]:
    if i.split("_")[0]=="FLARE22":
        cases.append(i[:15])
        
    else:
        cases.append(i[:10])


In [8]:
df["case"]=cases

In [9]:
df["case"].unique()

array(['Case_00001', 'Case_00002', 'Case_00003', 'Case_00004',
       'Case_00005', 'Case_00006', 'Case_00007', 'Case_00008',
       'Case_00009', 'Case_00010', 'Case_00011', 'Case_00012',
       'Case_00013', 'Case_00014', 'Case_00015', 'Case_00016',
       'Case_00017', 'Case_00018', 'Case_00019', 'Case_00020',
       'Case_00021', 'Case_00022', 'Case_00023', 'Case_00024',
       'Case_00025', 'Case_00026', 'Case_00027', 'Case_00028',
       'Case_00029', 'Case_00030', 'Case_00031', 'Case_00032',
       'Case_00033', 'Case_00034', 'Case_00035', 'Case_00036',
       'Case_00037', 'Case_00038', 'Case_00039', 'Case_00040',
       'Case_00041', 'Case_00042', 'Case_00043', 'Case_00044',
       'Case_00045', 'Case_00046', 'Case_00047', 'Case_00048',
       'Case_00049', 'Case_00050', 'Case_00051', 'Case_00052',
       'Case_00053', 'Case_00054', 'Case_00055', 'Case_00056',
       'Case_00057', 'Case_00058', 'Case_00059', 'Case_00060',
       'Case_00061', 'Case_00062', 'Case_00063', 'Case_

In [10]:
df

image_name                       contour_name  \
0           Case_00001_0000_slice000.png       Case_00001_0000_slice000.png   
1           Case_00001_0000_slice001.png       Case_00001_0000_slice001.png   
2           Case_00001_0000_slice002.png       Case_00001_0000_slice002.png   
3           Case_00001_0000_slice003.png       Case_00001_0000_slice003.png   
4           Case_00001_0000_slice004.png       Case_00001_0000_slice004.png   
...                                  ...                                ...   
26594  FLARE22_Tr_0050_0000_slice090.png  FLARE22_Tr_0050_0000_slice090.png   
26595  FLARE22_Tr_0050_0000_slice091.png  FLARE22_Tr_0050_0000_slice091.png   
26596  FLARE22_Tr_0050_0000_slice092.png  FLARE22_Tr_0050_0000_slice092.png   
26597  FLARE22_Tr_0050_0000_slice093.png  FLARE22_Tr_0050_0000_slice093.png   
26598  FLARE22_Tr_0050_0000_slice094.png  FLARE22_Tr_0050_0000_slice094.png   

                  case  
0           Case_00001  
1           Case_00001  
2           Case_00001  
3           Case_00001  
4           Case_00001  
...                ...  
26594  FLARE22_Tr_0050  
26595  FLARE22_Tr_0050  
26596  FLARE22_Tr_0050  
26597  FLARE22_Tr_0050  
26598  FLARE22_Tr_0050  

[26599 rows x 3 columns]

In [11]:
df.loc[df['case'] == "Case_00001"]

image_name                  contour_name        case
0    Case_00001_0000_slice000.png  Case_00001_0000_slice000.png  Case_00001
1    Case_00001_0000_slice001.png  Case_00001_0000_slice001.png  Case_00001
2    Case_00001_0000_slice002.png  Case_00001_0000_slice002.png  Case_00001
3    Case_00001_0000_slice003.png  Case_00001_0000_slice003.png  Case_00001
4    Case_00001_0000_slice004.png  Case_00001_0000_slice004.png  Case_00001
..                            ...                           ...         ...
265  Case_00001_0000_slice265.png  Case_00001_0000_slice265.png  Case_00001
266  Case_00001_0000_slice266.png  Case_00001_0000_slice266.png  Case_00001
267  Case_00001_0000_slice267.png  Case_00001_0000_slice267.png  Case_00001
268  Case_00001_0000_slice268.png  Case_00001_0000_slice268.png  Case_00001
269  Case_00001_0000_slice269.png  Case_00001_0000_slice269.png  Case_00001

[270 rows x 3 columns]

In [12]:
df.to_csv("absolute_meta.csv",index=False)

In [22]:
for i in df["case"]:
    if i[:4]=="Case":
        print(i)

Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001
Case_00001

In [13]:

def load_png_images_from_folder(folder_path):
    images = []
    for filename in sorted(os.listdir(folder_path)):  # Sort files to maintain order
        if filename.endswith(".png"):
            img_path = os.path.join(folder_path, filename)
            img = Image.open(img_path).convert('L')  # Convert to grayscale
            img_data = np.array(img)
            images.append(img_data)
    return np.array(images)

In [3]:
arr=load_png_images_from_folder("/mnt/ai_neuro/august_kun/miccai/samples/translated")
arr.shape

(270, 512, 512)

In [4]:
arr.shape

(270, 512, 512)

In [7]:
df

NameError: name 'df' is not defined

In [5]:
vol_1="/mnt/ai_neuro/august_kun/data/FLARE22Train/images/volumes/FLARE22_Tr_0001_0000.nii.gz"
seg_1="/mnt/ai_neuro/august_kun/data/FLARE22Train/labels/segmentations/FLARE22_Tr_0001.nii.gz"
vol=nib.load(vol_1)
seg=nib.load(seg_1)

vol_header=vol.header
vol_affine=vol.affine
vol_arr=vol.get_fdata()

In [6]:
vol_affine

array([[   0.64453101,    0.        ,    0.        , -329.35534668],
       [   0.        ,    0.64453101,    0.        , -329.35534668],
       [   0.        ,    0.        ,    2.5       ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    1.        ]])

In [38]:
np.unique(nib.load("/mnt/ai_neuro/august_kun/data/PseudolabeledCase/pseudo_label_blackbean_flare22/Case_00001.nii.gz").get_fdata())

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13.])

In [14]:
for case_ in df["case"].unique():
    x=df.loc[df['case'] == case_]
    images=[]
    for i,rows in x.iterrows():

    #arr=load_png_images_from_folder("/mnt/ai_neuro/august_kun/miccai/samples/translated") #return array    
        img_path = os.path.join("/mnt/ai_neuro/august_kun/miccai/ContourDiff/data/ct_2_mr",rows["image_name"])
        img = Image.open(img_path).convert('L')  # Convert to grayscale
        img_data = np.array(img)
        images.append(img_data)
    arr=np.array(images)


    vol_nii=case_+"_0000.nii.gz"
    seg_nii=case_+".nii.gz"
    if case_[:7]=="FLARE22":
        vol_1=f"/mnt/ai_neuro/august_kun/data/FLARE22Train/images/volumes/{vol_nii}"
    #"/mnt/ai_neuro/august_kun/data/UnlabeledCase"
    elif case_[:4]=="Case":
        vol_1=f"/mnt/ai_neuro/august_kun/data/UnlabeledCase/{vol_nii}"

    
    vol=nib.load(vol_1)

    vol_header=vol.header
    vol_affine=vol.affine
    del vol

    image_data_3d_flipped = arr[:, :, ::-1]
    image_data_3d = np.transpose(image_data_3d_flipped, (1, 2, 0))
    image_data_3d = np.rot90(image_data_3d, k=1, axes=(0, 1))
    nifti_image = nib.Nifti1Image(image_data_3d, vol_affine)

    #print(f"/mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/segmentations/{seg_nii}")
    #print(f"/mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/volumes/{case_}_0000.nii.gz")

    # Step 3: Save the NIfTI image as a .nii.gz file
    if case_[:7]=="FLARE22":
        shutil.copy(f"/mnt/ai_neuro/august_kun/data/FLARE22Train/labels/segmentations/{seg_nii}",f"/mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/segmentations/{seg_nii}")
    else:
        shutil.copy(f"/mnt/ai_neuro/august_kun/data/PseudolabeledCase/pseudo_label_blackbean_flare22/{seg_nii}",f"/mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/segmentations/{seg_nii}")
    nib.save(nifti_image,f"/mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/volumes/{case_}_0000.nii.gz")


In [5]:
ex=nib.load("/mnt/ai_neuro/august_kun/data/PseudolabeledCase/pseudo_label_blackbean_flare22/Case_00001.nii.gz")

In [6]:
ex.get_fdata().shape

(512, 512, 270)

In [18]:
v_p=sorted(glob.glob("/mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/volumes/*.nii.gz"))
s_p=sorted(glob.glob("/mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/segmentations/*.nii.gz"))
for i in range(len(v_p)):
    x=nib.load(v_p[i]).get_fdata()
    y=nib.load(s_p[i]).get_fdata()
    if x.shape!=y.shape:
        print(x.shape ,"-------",y.shape)
        print(v_p[i],"------",s_p[i])
        print(np.unique(y))


(512, 512, 329) ------- (512, 512, 518)
/mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/volumes/Case_00079_0000.nii.gz ------ /mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/segmentations/Case_00079.nii.gz
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
(512, 512, 2) ------- (512, 512, 93)
/mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/volumes/Case_00080_0000.nii.gz ------ /mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/segmentations/Case_00080.nii.gz
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
(512, 512, 1) ------- (512, 512, 89)
/mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/volumes/Case_00081_0000.nii.gz ------ /mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/segmentations/Case_00081.nii.gz
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
(512, 512, 1) ------- (512, 512, 168)
/mnt/ai_neuro/august

In [24]:
i = sitk.ReadImage("/mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/volumes/Case_00001.nii.gz")
i_np =sitk.GetArrayFromImage(i)
name = os.path.basename("/mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/volumes/Case_00001.nii.gz").split(".")[0]

# Normalize and convert the image data to uint8 or uint16
if i_np.dtype in [np.float32, np.float64]:
    # Normalize to 0-1 and scale to 0-255 for uint8
    i_np = (i_np - np.min(i_np)) / (np.max(i_np) - np.min(i_np))
    i_np = (i_np * 255).astype(np.uint8)  # Convert to uint8
elif i_np.dtype in [np.int32, np.int64, np.int16]:
    # Normalize the data to fit within uint16
    i_np = np.clip(i_np, 0, 65535).astype(np.uint16)
elif i_np.dtype == np.uint16:
    # Ensure data is within uint16 range
    i_np = np.clip(i_np, 0, 65535).astype(np.uint16)
elif i_np.dtype == np.uint8:
    # Ensure data is within uint8 range
    i_np = np.clip(i_np, 0, 255).astype(np.uint8)
else:
    raise TypeError(f"Unsupported image data type: {i_np.dtype}")

#print(f"Processed image {name} with shape {i_np.shape} and dtype {i_np.dtype}")

# Ensure the output directory exists
output_dir = "/mnt/ai_neuro/august_kun/miccai/flare24/nnUNet/nnunetv2/data_png_saved"

# Save each slice as a separate PNG file
for slice_index in range(i_np.shape[0]):
    slice_np = i_np[slice_index, :, :]
    zoom_factors = [512 / slice_np.shape[0], 512 / slice_np.shape[1]]
    slice_resized = zoom(slice_np, zoom_factors, order=3)
    slice_img = sitk.GetImageFromArray(slice_resized)
    slice_path = os.path.join(
        output_dir,
        f"{name}_slice{slice_index:03d}.png")
    sitk.WriteImage(slice_img, slice_path)

RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105:
sitk::ERROR: Unable to determine ImageIO reader for "/mnt/ai_neuro/august_kun/miccai/flare24/datasets/nnunet_data/segmentation/volumes/Case_00001.nii.gz"