In [12]:
import numpy as np
import shutil

import os


import SimpleITK as sitk
import glob

In [14]:
image_list=sorted(glob.glob("/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/nnUNet_raw/Dataset500_FLARE/imagesTr/*.nii.gz"))
label_list=sorted(glob.glob("/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/nnUNet_raw/Dataset500_FLARE/labelsTr/*.nii.gz"))
for image_file, label_file in zip(image_list, label_list):
    image = sitk.ReadImage(image_file)
    label = sitk.ReadImage(label_file)

    image_array = sitk.GetArrayFromImage(image)
    label_array = sitk.GetArrayFromImage(label)

    print(f'Image: {image_file}, Shape: {image_array.shape}')
    print(f'Label: {label_file}, Shape: {label_array.shape}')
    print('-'*50)

    if image_array.shape != label_array.shape:
        print(f'Mismatch found: {image_file} and {label_file}')
        print("x"*50)


Image: /Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/nnUNet_raw/Dataset500_FLARE/imagesTr/FLARE_000_0000.nii.gz, Shape: (107, 512, 512)
Label: /Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/nnUNet_raw/Dataset500_FLARE/labelsTr/FLARE_000.nii.gz, Shape: (103, 512, 512)
--------------------------------------------------
Mismatch found: /Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/nnUNet_raw/Dataset500_FLARE/imagesTr/FLARE_000_0000.nii.gz and /Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/nnUNet_raw/Dataset500_FLARE/labelsTr/FLARE_000.nii.gz
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Image: /Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/nnUNet_raw/Dataset500_FLARE/imagesTr/FLARE_001_0000.nii.gz, Shape: (85, 512, 512)
Label: /Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/nnUNet_raw/Dataset500_FLARE/labelsTr/FLARE_001.nii.gz, Shape: (85, 512, 512)
---------------------

In [43]:
print(label_list[0])

/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/nnUNet_raw/Dataset050_FLARE/labelsTr/FLARE_014.nii.gz


In [3]:
a="/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/nnUNet_raw/Dataset100_SPINE/labelsTr/SPINE_000.nii.gz"

In [4]:
mask_l=glob.glob("/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/segmentation/volumes/*")
img_l=glob.glob("/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/segmentation/segmentations/*")

In [7]:
img_l

['/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/segmentation/segmentations/FLARE22_Tr_0033_0000.nii.gz',
 '/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/segmentation/segmentations/FLARE22_Tr_0043_0000.nii.gz',
 '/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/segmentation/segmentations/FLARE22_Tr_0001_0000.nii.gz',
 '/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/segmentation/segmentations/FLARE22_Tr_0014_0000.nii.gz',
 '/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/segmentation/segmentations/FLARE22_Tr_0008_0000.nii.gz',
 '/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/segmentation/segmentations/FLARE22_Tr_0026_0000.nii.gz',
 '/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/segmentation/segmentations/FLARE22_Tr_0011_0000.nii.gz',
 '/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/segmentation/segmentations/FLARE22_Tr_0023_0000.nii.gz',


In [8]:
for i in range(len(mask_l)):
    
    shutil.move(mask_l[i],os.path.dirname(img_l[0]))
    shutil.move(img_l[i],os.path.dirname(mask_l[0]))

In [2]:
mask=sik.ReadImage("/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/segmentation/volumes/FLARE22_Tr_0001.nii.gz")
mask_arr=sik.GetArrayFromImage(mask)

print(np.unique(mask_arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


In [6]:
path="/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/nnUNet_raw/"

for i in range(len(image_list)):
    mask=sik.ReadImage(image_list[i])
    #image=sik.ReadImage(label_list[i])
    #image_arr=sik.GetArrayFromImage(image)
    mask_arr=sik.GetArrayFromImage(mask)

    #print(np.unique(image_arr))
    
    print(np.unique(mask_arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  1  2  3  4  5  6  7  8  9 1

In [37]:
np.unique(mask_arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
      dtype=uint16)

In [17]:
len(image_list),len(label_list)
image_list[0].split("/")

['',
 'Users',
 'kunkerdthaisong',
 'intern_cariva',
 'flare24',
 'datasets',
 'nnunet_data',
 'nnUNet_raw',
 'Dataset050_FLARE',
 'labelsTr',
 'FLARE_014.nii.gz']

In [29]:



for i in range(len(image_list)):
    shutil.move(image_list[i],os.path.dirname(label_list[0]))
    shutil.move(label_list[i],os.path.dirname(image_list[0]))

In [28]:
os.path.dirname(label_list[0])

'/Users/kunkerdthaisong/intern_cariva/flare24/datasets/nnunet_data/nnUNet_raw/Dataset050_FLARE/labelsTr'